### ISSUE TITLE
get_chunk method in batch_geochat_scene.py seems to be undefined

### ISSUE THREAD

**Issue by muazkashif** [mbzuai-oryx/GeoChat#33]
Traceback (most recent call last):
  File "/content/GeoChat/geochat/eval/batch_geochat_scene.py", line 139, in <module>
    eval_model(args)
  File "/content/GeoChat/geochat/eval/batch_geochat_scene.py", line 49, in eval_model
    questions = get_chunk(questions, args.num_chunks, args.chunk_idx)
NameError: name 'get_chunk' is not defined

**Comment by Hoteryoung** [comment]
You can copy the get_chunk() and split_list() funcs from other evalution .py files.
